### PR TITLE
Part two answer

### PR DESCRIPTION
**Pull request by kathalonso**

### CODE REVIEW

**Review by connormgerrits — COMMENTED** [review]
Grade: 100%

Awesome job, love the "katculator" and inclusion of an exponent button!
Just as a note, while your pull request was technically for the correct branch, it would appear that you pushed up an outdated file, however I saw your final submission on the first answer branch and am grading based on that. So for future assignments just be sure to double-check that the right file(s) are being pushed up to the remote repo from the local branch that youre on in VS code, no worries this time around as everyone is still just getting their bearings though!

HW Explanation Video #1: https://drive.google.com/file/d/1gaKyA4NlAFYYGJZXPED-JNMq_tH6Uq_Z/view?usp=sharing

HW Explanation Video #2: https://drive.google.com/file/d/1LaKsj4bwFBCi0HkmeltCJFXoRKWkryzd/view?usp=sharing

**Comment by kathalonso** [comment]
Hi Connor,
I worked on my first branch which was "part-one-something," made most of my
changes there. And then we were assigned to make another branch called
"part-two-something." I knew something looked off, I'll have to look more
into it. My thought was: whatever changes I made to my second branch ...
they would be applied to the master branch. And my first branch's changes
would be there on master as well. Was this not what happened?

I'll look at the videos tomorrow when I have time during the day.

**Comment by kathalonso** [comment]
How can I make sure my part-one-answer is the main branch I want to show in my repo? Do I merge ...? Do I delete part-two-answer? How can we go about this? Ty!

**Comment by johnny-rice** [comment]
RE "How can I make sure my part-one-answer is the main branch I want to show in my repo? Do I merge ...?"
>> Yes! Merge to master to.

**Comment by kathalonso** [comment]
Thanks, John! Miss you!

**Pull request merged**
